# Generated by Django 5.2.2 on 2025-06-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='page',
        ),
    ]
